### ISSUE TITLE
blank page sometimes

### ISSUE THREAD

**Issue by boniek83** [similarweb/statusbay#210]
**What happened**:
Some deployments cause statusbay to display blank page (to be precise - page renders correctly and then in split second rerenders blank). Why I think that is? Because when I set number of rows returned to not contain problematic deployment page loads normally. 

Contents of my firefox console when page is blank (normally this does not occur):
`TypeError: a is undefined
Tooltip.js:449:18
    P Tooltip.js:449
    React 6
    wl self-hosted:920
    Qi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    Aa self-hosted:977
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
        pa
        $a
        Ps
        Al
        Ml
        wl
        Qi
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Xi
        Qi
        Zi
        gl
        Aa
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156`

**What you expected to happen**:
There should be something more useful than blank page generated.
**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately - no idea ;)
**Anything else we need to know?**:

**Environment**:
- StatusBay version: latest from helm chart (as of 17.03.2020)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Kubernetes 1.15.9

**Comment by liorbd** [comment]
@kaplanelad It is possible that status of one application isn't one of 
```running, successful, failed, timeout, deleted``` ?
Anyway i'll add a fix that will show empty status in those cases.

**Comment by kaplanelad** [comment]
Hey @liorbd, yes we have also `cancelled` status

**Comment by liorbd** [comment]
@kaplanelad So maybe we shouldn't show this deployments, And filter them out in the API?

**Comment by boniek83** [comment]
I'm still getting blank page with similarweb/statusbay:release-0.1.7-rc1. This time to trigger it I have to filter status by setting it to cancelled. Page reloads empty with following errors in browsers console:

TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Xi
        Qi
        Zi
        gl
        Aa
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
TypeError: a is undefined
Tooltip.js:449:18

​

**Comment by kaplanelad** [comment]
Thanks, @boniek83, 
@liorbd can you please try to reproduce it?

**Comment by kaplanelad** [comment]
Hey @boniek83,
We have uploaded a hotfix. 
Can you please try the version: release-0.1.7-rc2?

**Comment by boniek83** [comment]
Firefox console logs:
```
09:24:47.609 TypeError: a is undefined
Tooltip.js:449:18
    P Tooltip.js:449
    React 6
    wl self-hosted:891
    Qi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    Aa self-hosted:948
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
09:24:47.609
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
09:24:47.609
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
09:24:47.609
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
09:24:47.609
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
09:24:47.609
TypeError: "a is undefined"
    P Tooltip.js:449
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    p ApplicationsHooks.js:43
    emit index.js:133
    onevent socket.js:278
    onpacket socket.js:240
    exports index.js:21
    emit index.js:133
    ondecoded manager.js:345
    exports index.js:21
    emit index.js:133
    add index.js:251
    ondata manager.js:335
    exports index.js:21
    emit index.js:133
    onPacket socket.js:461
    setTransport socket.js:278
    emit index.js:133
    onPacket transport.js:149
    onData transport.js:141
    onmessage websocket.js:156
react-dom.production.min.js:196:194
```
Running:
```
deployment.extensions/statusbay-statusbay-helm-api                  2/2     2            2           56d   statusbay-helm-api                  similarweb/statusbay:release-0.1.7-rc2   app=statusbay-helm,component=statusbay-statusbay-helm-api,release=statusbay
deployment.extensions/statusbay-statusbay-helm-ui                   3/3     3            3           56d   statusbay-helm-ui                   similarweb/statusbay-ui:0.1.6            app=statusbay-helm,component=statusbay-statusbay-helm-ui,release=statusbay
deployment.extensions/statusbay-statusbay-helm-watcher-kubernetes   1/1     1            1           56d   statusbay-helm-watcher-kubernetes   similarweb/statusbay:release-0.1.7-rc2   app=statusbay-helm,component=statusbay-statusbay-helm-watcher-kubernetes,release=statusbay
```

**Comment by kaplanelad** [comment]
@liorbd FYI

@boniek83, can you please run  run this query `select distinct status from kubernetes` in DB and share with us the results?

**Comment by boniek83** [comment]
> mysql> select distinct status from kubernetes;
> +------------+
> | status     |
> +------------+
> | successful |
> | deleted    |
> | cancelled  |
> | failed     |
> +------------+
> 4 rows in set (0.00 sec)

**Comment by kaplanelad** [comment]
Thanks. 
I'll continue investigate the issue.

**Comment by boniek83** [comment]
It works. Thanks!
